[package]
name = "hyper-unix-connector"
version = "0.1.4"
authors = ["Akshay Narayan <akshayn@mit.edu>"]
edition = "2018"
description = "Use hyper with unix-domain sockets"
homepage = "https://github.com/akshayknarayan/hyper-unix-connector"
repository = "https://github.com/akshayknarayan/hyper-unix-connector"
license = "ISC"

[dependencies]
failure = "0.1"
futures-util = "0.3.1"
hex = "0.4"
hyper = { version = "0.13", features = ["stream"] }
tokio = { version = "0.2", features = ["uds"] }
pin-project = "0.4"
